# Generated by Django 4.1 on 2023-10-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255)),
                ("post", models.CharField(max_length=255)),
                ("name_organization", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "employee",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GeographicalObject",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("feature", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("size", models.IntegerField(blank=True, null=True)),
                ("describe", models.CharField(blank=True, max_length=1000, null=True)),
                ("url_photo", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "photo_byte",
                    models.BinaryField(blank=True, editable=True, null=True),
                ),
                ("status", models.BooleanField()),
            ],
            options={
                "db_table": "geographical_object",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "location",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MarsStation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type_status", models.CharField(max_length=255)),
                ("date_create", models.DateField()),
                ("date_form", models.DateField()),
                ("date_close", models.DateField()),
                ("status_task", models.IntegerField()),
                ("status_mission", models.IntegerField()),
            ],
            options={
                "db_table": "mars_station",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Transport",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("describe", models.CharField(blank=True, max_length=1000, null=True)),
                ("url_photo", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "photo_byte",
                    models.BinaryField(blank=True, editable=True, null=True),
                ),
            ],
            options={
                "db_table": "transport",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("login", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("admin", models.BooleanField()),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
    ]
