# Generated by Django 4.1 on 2023-09-13 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bmstu_lab", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE location
            ADD CONSTRAINT FR_location_geografic_object
                FOREIGN KEY (id_geografic_object) REFERENCES geografic_object (id);

            ALTER TABLE location
            ADD CONSTRAINT FR_location_transport
                FOREIGN KEY (id_transport) REFERENCES transport (id);

            ALTER TABLE history_movement
            ADD CONSTRAINT FR_history_movement_begin_location
                FOREIGN KEY (id_begin_location) REFERENCES location (id);

            ALTER TABLE history_movement
            ADD CONSTRAINT FR_history_movement_end_location
                FOREIGN KEY (id_end_location) REFERENCES location (id);
            """
        ),
    ]
